### ISSUE TITLE
Keiko crashes on utf8 chars in glossary files.

### ISSUE THREAD

**Issue by underdarknl** [minvws/nl-kat-keiko#22]
When generating a report Keiko will crash if any if the glossary strings contain utf8 chars.

```
2023/02/08 17:17:21 [error] 4006347#4006347 [unit] #100210: Python failed to call 'future.result()'
Traceback (most recent call last):
  File "/var/www/katkeiko_v1.5.1/.venv/lib/python3.8/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/var/www/katkeiko_v1.5.1/.venv/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/var/www/katkeiko_v1.5.1/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/var/www/katkeiko_v1.5.1/.venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/var/www/katkeiko_v1.5.1/.venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
    raise exc
  File "/var/www/katkeiko_v1.5.1/.venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/var/www/katkeiko_v1.5.1/.venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/var/www/katkeiko_v1.5.1/.venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/var/www/katkeiko_v1.5.1/.venv/lib/python3.8/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/var/www/katkeiko_v1.5.1/.venv/lib/python3.8/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/var/www/katkeiko_v1.5.1/.venv/lib/python3.8/site-packages/starlette/routing.py", line 68, in app
    await response(scope, receive, send)
  File "/var/www/katkeiko_v1.5.1/.venv/lib/python3.8/site-packages/starlette/responses.py", line 170, in __call__
    await self.background()
  File "/var/www/katkeiko_v1.5.1/.venv/lib/python3.8/site-packages/starlette/background.py", line 43, in __call__
    await task()
  File "/var/www/katkeiko_v1.5.1/.venv/lib/python3.8/site-packages/starlette/background.py", line 28, in __call__
    await run_in_threadpool(self.func, *self.args, **self.kwargs)
  File "/var/www/katkeiko_v1.5.1/.venv/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/var/www/katkeiko_v1.5.1/.venv/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/var/www/katkeiko_v1.5.1/.venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/var/www/katkeiko_v1.5.1/.venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/var/www/katkeiko_v1.5.1/keiko/keiko.py", line 47, in generate_report
    glossary_entries = read_glossary(glossary)
  File "/var/www/katkeiko_v1.5.1/keiko/keiko.py", line 172, in read_glossary
    _ = next(csvreader)
  File "/usr/lib/python3.8/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3565: ordinal not in range(128)
```

**Comment by underdarknl** [comment]
This probably fixes it, line 170 in keiko/keiko.py 
`csvreader = csv.reader(glossary_file)`
should specify the encoding
`csvreader = csv.reader(glossary_file, encoding="utf8")`

**Comment by Lisser** [comment]
I think the encoding should be passed to the file-handler:
```python
with open(glossary_file_path, encoding="utf-8") as glossary_file:
    csvreader = csv.reader(glossary_file)
```

as per the docs: https://docs.python.org/3/library/csv.html#examples

**Comment by ammar92** [comment]
This indeed depends on the system's default encoding (which is almost always UTF8 in most docker images as far as I've seen). If the format is explicitly written as a UTF8 format, then we should explicitly decode it as such, regardless of the system's default encoding.
